baseURL = 'http://blog.przhome.xyz/'
languageCode = 'en-us'
title = 'przhome.xyz'
theme = 'lightbi-hugo'

[Params]
    useHLJS = true
    # Do i need to upload those assets in the assets directory here ? 
    selfHosted = false
